server:
  port: 8000
  tomcat: uri-encoding:utf-8
spring:
  datasource:
    primary:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://10.1.7.151:3306/authorize
      username: root
      password: 123456
      maximumPoolSize: 5
    secondary:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://10.1.7.151:3306/authorize_gz
      username: root
      password: 123456
      maximumPoolSize: 5
  thymeleaf:
   cache: false
   prefix: classpath:/templates/
   suffix: .html
   encoding: UTF-8
   content-type: text/html
   mode: HTML5
logging:
  file: /logging/anime/One/application.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
      root: ERROR
      org.springframework.web: ERROR
      org.hibernate: ERROR
      com.anmi.anime: INFO